# Generated by Django 3.0.3 on 2020-03-05 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50, verbose_name='Имя пользователя')),
                ('user_surname', models.CharField(max_length=50, verbose_name='Фамилия пользователя')),
                ('user_patronymic', models.CharField(max_length=50, verbose_name='Отчество пользователя')),
                ('user_email', models.EmailField(max_length=50, verbose_name='Email пользователя')),
                ('user_birthdate', models.DateTimeField(verbose_name='Дата рождения')),
                ('user_reg_date', models.DateTimeField(verbose_name='Дата регистрации')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
