# Generated by Django 3.0.4 on 2020-03-27 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0005_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(default='undistributed', max_length=50, verbose_name='Тип пользователя')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.Project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.User')),
            ],
            options={
                'verbose_name': 'Участник проекта',
                'verbose_name_plural': 'Участники проектов',
            },
        ),
    ]
