# Generated by Django 3.0.4 on 2020-03-27 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0006_projectusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task_title', models.CharField(max_length=255, verbose_name='Заголовок задания')),
                ('task_description', models.TextField(max_length=3000, verbose_name='Описание задания')),
                ('task_creation_date', models.DateTimeField(verbose_name='Дата создания задания')),
                ('start_date', models.DateTimeField(verbose_name='Начало выполнения задания')),
                ('end_date', models.DateTimeField(verbose_name='Конец выполнения задания')),
                ('done', models.BooleanField(default=False, verbose_name='Задание выполнено')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.Project')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('test', models.TextField(max_length=3000, verbose_name='Текст TODO')),
                ('done', models.BooleanField(default=False, verbose_name='TODO выполнено')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.Task')),
            ],
        ),
        migrations.CreateModel(
            name='TaskUsers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.Task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='signUp.User')),
            ],
            options={
                'verbose_name': 'Ответственный за задание',
                'verbose_name_plural': 'Ответственные за задания',
            },
        ),
    ]
