# Generated by Django 3.0.4 on 2020-03-27 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0007_task_taskusers_todo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='test',
            new_name='text',
        ),
    ]
