# Generated by Django 3.0.4 on 2020-03-27 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signUp', '0008_auto_20200327_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Публичное задание'),
        ),
    ]
